# Discord bot token here
token: ""

# Random bot config
bot-status: "ONLINE"

# Time in seconds between each bot activity
activity-change-interval: 20

# Config for the auto PIX code generator
auto-pix:
  chave-pix: ""
  name: ""
  city: ""